version: "3.8"

services:
  app:
    container_name: app
    #build dockerfile
    build:
      context: "./app" # path lokasi dockerfile nya
      dockerfile: Dockerfile # nama dockerfile
    image: "app-golang:1.0.0" # nama image, dufault akan di buat nama random
    environment:
      - "APP_PORT=8080"
    ports: # expose port
      - "8080:8080"
